M48
; DRILL file {KiCad 9.0.6} date 2026-01-24T13:37:30-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-24T13:37:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.500
%
G90
G05
T1
X159.965Y-82.22
X164.815Y-82.22
T2
X159.665Y-79.19
X165.115Y-79.19
T3
X241.0Y-80.0
X241.0Y-125.5
M30
