M48
; DRILL file {KiCad 9.0.5} date 2026-01-31T13:27:37-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-31T13:27:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1772
%
G90
G05
T1
X9.4078Y-3.2045
X9.5988Y-3.2045
T2
X9.396Y-3.3238
X9.6106Y-3.3238
T3
X7.6771Y-1.4961
X7.6771Y-3.2667
M30
